apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: default
  labels:
    app: postgres
data:
  POSTGRES_HOST: postgres-host
  POSTGRES_PORT: postgres-port
  POSTGRES_DB: postgres-db
